package:
    name: brainmodels
    version: "0.2.1"

source:
    path: ../../

build:
    number: 0 
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    host:
        - python==3.8
        - setuptools>=24
        - numpy>= 1.13
        - sympy>=1.2
        - numba>=0.40
        - brainpy>=0.3.0
    run:
        - python==3.8
        - numpy>=1.13
        - sympy>=1.2
        - numba>=0.40
        - matplotlib>=3.0
        - setuptools>=24
        - autopep8
        - brainpy

test:
  imports:
    - brainmodels

about:
    home: https://github.com/PKU-NIP-Lab/BrainPy-Models
    license: GPL-3.0
    summary: 'Implementations of cononical neuron, synapse and network models, using neuronal dynamics simulation framework BrainPy.'
    description: |
        BrainPy-Models is a repository accompanying neuronal 
        dynamics simulation framework BrainPy. It includes 
        implementations of the most canonical and effective 
        neuron, synapse and network models. Users can learn
        how to run a computational neuroscience simulation
        from our tutorials or easily call those models through 
        specific apis to use them without rewrite.
    dev_url: https://github.com/PKU-NIP-Lab/BrainPy-Models
    doc_url: https://brainpy-models.readthedocs.io/en/latest/
    doc_source_url: https://github.com/PKU-NIP-Lab/BrainPy-Models/blob/main/README.rst